openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Story:
      type: "object"
      required:
        - id
        - title
        - author
      properties:
        id:
          type: "number"
        title:
          type: "string"
        author:
          type: "string"
  parameters:
    id:
      name: "id"
      description: "Id of the story"
      in: "path"
      required: True
      schema:
        type: "number"

paths:
  /stories:
    get:
      operationId: "stories.read_all"
      tags:
        - "Stories"
      summary: "Read the list of stories"
      responses:
        "200":
          description: "Successfully read stories list"
    post:
      operationId: "stories.create"
      tags:
        - Stories
      summary: "Create a person"
      requestBody:
        description: "Story to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "story"
              $ref: "#/components/schemas/Story"
      responses:
        "201":
          description: "Successfully created person"
  /stories/{id}:
    get:
      operationId: "stories.read_one"
      tags:
        - Stories
      summary: "Read one story"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Successfully read story"
    put:
      operationId: "stories.update"
      tags:
        - Stories
      summary: "Update a story"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Successfully updated story"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "story"
              $ref: "#/components/schemas/Story"
    delete:
      tags:
        - Stories
      operationId: "stories.delete"
      summary: "Delete a story"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "204":
          description: "Successfully deleted story"